global:
#     # ResolveTimeout is the time after which an alert is declared resolved
#     # if it has not been updated.
#     resolve_timeout: <duration>
#
#     # The default SMTP From header field.
#     smtp_from: <tmpl_string>
#     # The default SMTP smarthost used for sending emails, including port number.
#     # Port number usually is 25, or 587 for SMTP over TLS (sometimes referred to as STARTTLS).
#     # Example: smtp.example.org:587
#     smtp_smarthost: <string>
#     # The default hostname to identify to the SMTP server.
#     smtp_hello: <string>
#     smtp_auth_username: <string>
#     # SMTP Auth using LOGIN and PLAIN.
#     smtp_auth_password: <secret>
#     # SMTP Auth using PLAIN.
#     smtp_auth_identity: <string>
#     # SMTP Auth using CRAM-MD5.
#     smtp_auth_secret: <secret>
#     # The default SMTP TLS requirement.
#     smtp_require_tls: <bool>


route:
  receiver: 'slack'

receivers:
     - name: email

     - name: slack
       slack_configs:
           - send_resolved: true
             username: 'NUM Bridge Validators'
             channel: '#backend-alert'
             api_url: ''
             title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
             text: "*Details:* {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
